import { DEVICE_GROUPS, QUICK_WIDTHS, findDevice } from "./devices.js";
const brandTabs=document.getElementById("brandTabs"),deviceSelect=document.getElementById("deviceSelect"),deviceMeta=document.getElementById("deviceMeta"),quickWidths=document.getElementById("quickWidths"),statusLabel=document.getElementById("statusLabel"),statusViewport=document.getElementById("statusViewport"),tabTitle=document.getElementById("tabTitle"),powerBtn=document.getElementById("powerBtn"),rotateBtn=document.getElementById("rotateBtn"),applyBtn=document.getElementById("applyBtn"),resetBtn=document.getElementById("resetBtn"),applyCustomBtn=document.getElementById("applyCustomBtn"),customWidth=document.getElementById("customWidth"),customHeight=document.getElementById("customHeight"),customDpr=document.getElementById("customDpr"),errorBox=document.getElementById("errorBox");
let selectedBrandId="apple",selectedDeviceId="iphone-15-pro",selectedOrientation="portrait",currentState=null;
function setError(message){message=message||"";errorBox.hidden=!message;errorBox.textContent=message}
function send(message){return new Promise(function(resolve,reject){chrome.runtime.sendMessage(message,function(response){if(chrome.runtime.lastError){reject(new Error(chrome.runtime.lastError.message));return}resolve(response)})})}
function currentGroup(){return DEVICE_GROUPS.find(function(group){return group.id===selectedBrandId})||DEVICE_GROUPS[0]}
function renderBrandTabs(){brandTabs.innerHTML="";DEVICE_GROUPS.forEach(function(group){const b=document.createElement("button");b.type="button";b.className="brand-tab"+(group.id===selectedBrandId?" active":"");b.textContent=group.label;b.addEventListener("click",async function(){selectedBrandId=group.id;selectedDeviceId=group.devices[0].id;await chrome.storage.local.set({lastBrandId:selectedBrandId,lastDeviceId:selectedDeviceId});renderBrandTabs();renderDeviceOptions()});brandTabs.appendChild(b)})}
function renderDeviceOptions(){const group=currentGroup();deviceSelect.innerHTML="";group.devices.forEach(function(device){const o=document.createElement("option");o.value=device.id;o.textContent=device.label;deviceSelect.appendChild(o)});if(!group.devices.some(function(device){return device.id===selectedDeviceId})){selectedDeviceId=group.devices[0].id}deviceSelect.value=selectedDeviceId;renderDeviceMeta()}
function renderDeviceMeta(){const d=findDevice(selectedDeviceId);if(!d)return;const w=selectedOrientation==="portrait"?d.width:d.height,h=selectedOrientation==="portrait"?d.height:d.width;deviceMeta.textContent=w+" x "+h+" CSS px  •  DPR "+d.dpr+"  •  Touch"}
function renderOrientation(){document.querySelectorAll("[data-orientation]").forEach(function(b){b.classList.toggle("active",b.dataset.orientation===selectedOrientation)});renderDeviceMeta()}
function renderQuickWidths(){quickWidths.innerHTML="";QUICK_WIDTHS.forEach(function(p){const b=document.createElement("button");b.type="button";b.className="quick-btn";b.textContent=p.label;b.title=p.width+" x "+p.height;b.addEventListener("click",async function(){customWidth.value=p.width;customHeight.value=p.height;customDpr.value=p.dpr;await applyCustom()});quickWidths.appendChild(b)})}
function renderState(){const enabled=Boolean(currentState&&currentState.enabled);powerBtn.classList.toggle("active",enabled);rotateBtn.disabled=!enabled;if(!enabled){statusLabel.textContent="Desktop mode";statusViewport.textContent="Browser viewport";return}statusLabel.textContent=currentState.mode==="custom"?"Custom emulation":currentState.brand||"Mobile emulation";statusViewport.textContent=currentState.label+" — "+currentState.width+"x"+currentState.height+" @ "+currentState.dpr+"x";if(currentState.deviceId&&currentState.deviceId!=="custom"){const d=findDevice(currentState.deviceId);if(d){selectedDeviceId=d.id;selectedBrandId=d.groupId;selectedOrientation=currentState.orientation||"portrait";renderBrandTabs();renderDeviceOptions();renderOrientation()}}}
async function refreshState(){setError();const r=await send({type:"GET_STATE"});if(!r||!r.ok)throw new Error(r&&r.error?r.error:"Could not read extension state.");currentState=r.state;tabTitle.textContent=r.tab&&r.tab.title?r.tab.title:"Current tab";renderState()}
async function applyPreset(){setError();applyBtn.disabled=true;try{const r=await send({type:"APPLY_PRESET",deviceId:selectedDeviceId,orientation:selectedOrientation});if(!r||!r.ok)throw new Error(r&&r.error?r.error:"Could not apply device.");currentState=r.state;await chrome.storage.local.set({lastDeviceId:selectedDeviceId,lastBrandId:selectedBrandId,lastOrientation:selectedOrientation});renderState()}finally{applyBtn.disabled=false}}
async function applyCustom(){setError();const r=await send({type:"APPLY_CUSTOM",width:Number(customWidth.value),height:Number(customHeight.value),dpr:Number(customDpr.value),orientation:selectedOrientation,touch:true,mobile:true});if(!r||!r.ok)throw new Error(r&&r.error?r.error:"Could not apply custom viewport.");currentState=r.state;renderState()}
async function reset(){setError();const r=await send({type:"RESET"});if(!r||!r.ok)throw new Error(r&&r.error?r.error:"Could not reset desktop mode.");currentState=null;renderState()}
deviceSelect.addEventListener("change",async function(){selectedDeviceId=deviceSelect.value;await chrome.storage.local.set({lastDeviceId:selectedDeviceId});renderDeviceMeta()});
document.querySelectorAll("[data-orientation]").forEach(function(b){b.addEventListener("click",async function(){selectedOrientation=b.dataset.orientation;await chrome.storage.local.set({lastOrientation:selectedOrientation});renderOrientation()})});
applyBtn.addEventListener("click",function(){applyPreset().catch(function(e){setError(e.message)})});
applyCustomBtn.addEventListener("click",function(){applyCustom().catch(function(e){setError(e.message)})});
resetBtn.addEventListener("click",function(){reset().catch(function(e){setError(e.message)})});
rotateBtn.addEventListener("click",async function(){try{setError();const r=await send({type:"ROTATE"});if(!r||!r.ok)throw new Error(r&&r.error?r.error:"Could not rotate device.");currentState=r.state;selectedOrientation=currentState.orientation;renderOrientation();renderState()}catch(e){setError(e.message)}});
powerBtn.addEventListener("click",async function(){try{if(currentState&&currentState.enabled){await reset()}else{await applyPreset()}}catch(e){setError(e.message)}});
(async function(){try{const saved=await chrome.storage.local.get(["lastBrandId","lastDeviceId","lastOrientation"]);selectedBrandId=saved.lastBrandId||selectedBrandId;selectedDeviceId=saved.lastDeviceId||selectedDeviceId;selectedOrientation=saved.lastOrientation||selectedOrientation;renderBrandTabs();renderDeviceOptions();renderOrientation();renderQuickWidths();await refreshState()}catch(e){setError(e.message)}})();
